CREATE TABLE PRODUCTCATEGORYID (PRODUCTCATEGORYID INT NOT NULL PRIMARY KEY, NAME VARCHAR(255) NOT NULL);

CREATE TABLE PRODUCTFAMILYID (PRODUCTFAMILYID INTEGER NOT NULL PRIMARY KEY, PRODUCTCATEGORYID INTEGER NOT NULL, NAME VARCHAR(255) NOT NULL, FOREIGN KEY (PRODUCTCATEGORYID) REFERENCES PRODUCTCATEGORYID (PRODUCTCATEGORYID) ON DELETE CASCADE);

CREATE TABLE PRODUCTGROUPID (PRODUCTGROUPID INTEGER NOT NULL PRIMARY KEY, PRODUCTFAMILYID INTEGER NOT NULL, NAME VARCHAR(255) NOT NULL, FOREIGN KEY (PRODUCTFAMILYID) REFERENCES PRODUCTFAMILYID (PRODUCTFAMILYID) ON DELETE CASCADE);

CREATE TABLE ARTICLEID (ARTICLEID INTEGER NOT NULL PRIMARY KEY, PRODUCTGROUPID INTEGER NOT NULL, NAME VARCHAR(255) NOT NULL, PREIS REAL, FOREIGN KEY (PRODUCTGROUPID) REFERENCES PRODUCTGROUPID (PRODUCTGROUPID) ON DELETE CASCADE);

CREATE TABLE LANDID (LANDID INTEGER NOT NULL PRIMARY KEY, NAME VARCHAR(255) NOT NULL);

CREATE TABLE REGIONID (REGIONID INTEGER NOT NULL PRIMARY KEY, LANDID INTEGER NOT NULL, NAME VARCHAR(255) NOT NULL, FOREIGN KEY (LANDID) REFERENCES LANDID (LANDID) ON DELETE CASCADE);

CREATE TABLE STADTID (STADTID INTEGER NOT NULL PRIMARY KEY, REGIONID INTEGER NOT NULL, NAME VARCHAR(255) NOT NULL, FOREIGN KEY (REGIONID) REFERENCES REGIONID (REGIONID) ON DELETE CASCADE);

CREATE TABLE SHOPID (SHOPID INTEGER NOT NULL PRIMARY KEY, STADTID INTEGER NOT NULL, NAME VARCHAR(255) NOT NULL, FOREIGN KEY (STADTID) REFERENCES STADTID (STADTID) ON DELETE CASCADE);

CREATE TABLE SALES (DATE DATE NOT NULL, SHOPID INTEGER NOT NULL, ARTICLEID INTEGER NOT NULL, QUANTITY INTEGER NOT NULL, AMOUNT REAL NOT NULL, FOREIGN KEY (SHOPID) REFERENCES SHOPID (SHOPID) ON DELETE CASCADE, FOREIGN KEY (ARTICLEID) REFERENCES ARTICLEID (ARTICLEID) ON DELETE CASCADE);